### ISSUE TITLE
Nifty Row Code Review - Urgent

### ISSUE THREAD

**Issue by ggurbet** [Nifty-Row/casper-frontend#1]
Hello Nifty Row,

I am doing the code review for your app "CA - NiftyRow NFT & Security Tokens Marketplace Autosave'' on behalf of [CRDAO](https://crdao.ossa.dev/). There are some issues that need immediate attention. I've already emailed you using the one in the README, and also from the DEVxDAO Portal but did not receive a response. Please contact me at [t.me/ggurbet](https://t.me/ggurbet) so that they can be fixed as soon as possible.

**Comment by JayEs23** [comment]
@ggurbet , Thanks for reaching out. Please forward the email and any other materials to bolaji@niftyrow.com. We'll reach out on telegram as well. Cheers!.

**Comment by ggurbet** [comment]
Thanks for the reply @JayEs23. However, that email address is unreachable. I will be waiting for your message on Telegram. See you there!
